title: Learn By Doing
author: Forestry.io
email: hello@albert.io
description: >-
  Acheive mastery with world-class learning content on Albert.
base_url: http://127.0.0.1:4000
url: "" # your site's origin, e.g. https://forestry.io

asset_path: "/assets/img/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# collections: 
#   landing_pages: 
#     output: true
#     permalink: /:name
#   case-studies:
#     output: true
collections:
  case-studies:
    output: true
    permalink: "/case-studies/:path/"
  albert-academy:
    output: true
    permalink: "/albert-academy/:path/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
