title: Learn By Doing
author: Forestry.io
email: hello@albert.io
description: >-
  Acheive mastery with world-class learning content on Albert.
base_url: ""
url: "http://albert.io" # the base hostname & protocol for your site

asset_path: "/assets/img/"

# collections: 
#   landing_pages: 
#     output: true
#     permalink: /:name
#   case-studies:
#     output: true

permalink: /:slug

collections:
  case-studies:
    output: true
    permalink: "/case-studies/:name/"
  albert-academy:
    output: true
    permalink: "/albert-academy/:name/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-menus

sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
