---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: FORESTRY-README.md
  label: Welcome - First Steps
  read_only: true
- type: jekyll-posts
  label: Blog
  create: all
  templates:
  - post
- type: directory
  path: ''
  label: Pages
  create: documents
  match: "*.md"
  exclude: "{README.md, Albert Academy}"
  new_doc_ext: md
  templates:
  - landing_page
- type: directory
  path: _case-studies
  label: Case studies
  create: all
  match: "**/*"
  templates:
  - case-study
- type: directory
  path: _albert-academy
  label: Albert Academy
  create: all
  match: "**/*"
  templates:
  - albert-academy
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
